CREATE TABLE IF NOT EXISTS UserWordProgress (
    user_id VARCHAR(128) NOT NULL,
    word VARCHAR(255) NOT NULL,
    progress_data JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, word)
);
