// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_77n_S071h_9wNHB_LGWS7ix0od9Hl0',
    appId: '1:44193555309:web:c4b14c45b409910abb3064',
    messagingSenderId: '44193555309',
    projectId: 'mnemonics-76ca2',
    authDomain: 'mnemonics-76ca2.firebaseapp.com',
    storageBucket: 'mnemonics-76ca2.firebasestorage.app',
    measurementId: 'G-6YF7WZ4B9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmwx-A4jCl1rtnyUGf1mYhegampar3cE',
    appId: '1:44193555309:android:9d6b16595edc3bf2bb3064',
    messagingSenderId: '44193555309',
    projectId: 'mnemonics-76ca2',
    storageBucket: 'mnemonics-76ca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGwmGdq_qoqKo5M72lWcAUZLH7hDUtKzU',
    appId: '1:44193555309:ios:b287f56d6e41aa07bb3064',
    messagingSenderId: '44193555309',
    projectId: 'mnemonics-76ca2',
    storageBucket: 'mnemonics-76ca2.firebasestorage.app',
    iosBundleId: 'com.example.mnemonics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGwmGdq_qoqKo5M72lWcAUZLH7hDUtKzU',
    appId: '1:44193555309:ios:b287f56d6e41aa07bb3064',
    messagingSenderId: '44193555309',
    projectId: 'mnemonics-76ca2',
    storageBucket: 'mnemonics-76ca2.firebasestorage.app',
    iosBundleId: 'com.example.mnemonics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1_77n_S071h_9wNHB_LGWS7ix0od9Hl0',
    appId: '1:44193555309:web:ae6556bad30d0699bb3064',
    messagingSenderId: '44193555309',
    projectId: 'mnemonics-76ca2',
    authDomain: 'mnemonics-76ca2.firebaseapp.com',
    storageBucket: 'mnemonics-76ca2.firebasestorage.app',
    measurementId: 'G-QYK70X27EK',
  );
}
